# Generated by Django 4.0.3 on 2022-04-04 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('date_start', models.TimeField()),
                ('date_end', models.TimeField()),
                ('location', models.CharField(max_length=120)),
                ('owner', models.IntegerField()),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('CP', 'Complete'), ('IC', 'Incomplete'), ('IP', 'In progress'), ('CD', 'Canceled'), ('PD', 'Pending'), ('RM', 'Removed')], default='PD', max_length=2)),
            ],
        ),
    ]
