# Generated by Django 4.0.3 on 2022-04-07 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_tasks', '0004_task_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='owner',
        ),
    ]
